name: rating_bar
description: A customizable Rating Bar for flutter with half rating support
version: 0.2.0
author: Joshua Matta<joshuamatta1996@gmail.com>
homepage: https://github.com/joshmatta/rating_bar

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
